import Head from "next/head";
import styled from "styled-components";
import client from "../src/apollo/client";
import { GET_HOMEPAGE_BLOCKS } from "../src/queries/get-homepage-blocks";
import BlockSwitch from "../src/helper/blockSwitch";

export async function getStaticProps(context) {
  const { data, loading, networkStatus } = await client.query({
    query: GET_HOMEPAGE_BLOCKS(),
  });
  const blocks = data?.pageBy?.blocks;

  return {
    props: { blocks },
    revalidate: 1,
  };
}

export default function Home({ blocks }) {
  return (
    <>
      <Head>
        <title>Head Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1 style={{ textAlign: "center" }}>Hello World!</h1>
        {blocks.map((block, i) => BlockSwitch(block, i))}
      </Main>
    </>
  );
}

const Main = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  width: 100%;
  min-height: 100vh;
  background-color: beige;
`;
